// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: ChatGPT

#ifndef _CHATGPT_UI_H
#define _CHATGPT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_events.h"
extern lv_obj_t *ui_homeScreen;
extern lv_obj_t *ui_titlePanel;
extern lv_obj_t *ui_appIcon;
extern lv_obj_t *ui_titleText;
extern lv_obj_t *ui_wifiIcon;
extern lv_obj_t *ui_appPanel;
extern lv_obj_t *ui_scrollPanel;
extern lv_obj_t *ui_chatPanel;
extern lv_obj_t *ui_actionPanel;
void ui_event_promptText( lv_event_t * e);
extern lv_obj_t *ui_promptText;
void ui_event_sendButton( lv_event_t * e);
extern lv_obj_t *ui_sendButton;
extern lv_obj_t *ui_keyboard;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_electron_32_png);   // assets\electron_32.png
LV_IMG_DECLARE( ui_img_wifi_w_png);   // assets\wifi_w.png
LV_IMG_DECLARE( ui_img_up_arrow_png);   // assets\up_arrow.png
LV_IMG_DECLARE( ui_img_electron_png);   // assets\electron.png
LV_IMG_DECLARE( ui_img_user_a_png);   // assets\user_a.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
